type: 'kitti'
root_dir: '.'

data_dir: './data/kitti'
raw_data_dir: './data/kitti/raw_data'
KITTI3D_data_dir: './data/kitti/KITTI3D/training'
KITTI_merge_data_dir: './data/kitti/kitti_merge/training'

writelist: ['Car']
label_mode: ['high_acc']
#optional: label_mode: ['low_cost'] or label_mode: ['high_acc', 'low_cost']

